server:
  tomcat:
    max-http-form-content-size: 50MB
    max-swallow-size: 50MB
    connection-timeout: 600000
    keep-alive-timeout: 600000

spring:
  application:
    name: youlai-boot
  profiles:
    active: prod
  config:
    import: classpath:codegen.yml
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
# 在 banner.txt 中显示项目版本，使用 @project.version@ 从 pom.xml 获取
project:
  version: @project.version@
